module.exports = function(grunt) {
grunt.initConfig({
	less: {
        development: {
            files: {
                'app/style/css/app.css' : 'app/style/less/app.less'
            }
      }
    },
    watch: {
      scripts: {
        files: ['**/*.less'],
        tasks: ['less'],
        options: {
          spawn: false,
        },
      },
      templates: {
        files: ['app/partials/**/*.html'],
        tasks: ['ngtemplates:skywarp']
      }
    },
    clean: {
        dist: ['dist']
    },
    copy: {
        main: {
            src: ['app/**', '!app/style/less/**', '!app/partials/**'],
            dest: 'dist/'
        }
    },
    uglify: {
        options: {
          compress: {
            drop_console: true
          }
        },
        dist: {
          files: [{
              expand: true,
              cwd: 'dist/app/js',
              src: '**/*.js',
              dest: 'dist/app/js'
          }]
        }
    },   
    cssmin: {
        minify: {
            expand: true,
            cwd: 'dist/app/style/css/',
            src: ['**/*.css', '!*.min.css'],
            dest: 'dist/app/style/css/'
        }
    },
    nightwatch: {
        options: {
            settings: {
                src_folders: ["test"],
                output_folder: "test/reports",
            },
            test_settings: {
                selenium_host: '127.0.0.1',
                selenium_port: 4444,
                blnk_url: 'http://blnk.vagrant',
                blnk_user: 'weather@blnk.vagrant',
                blnk_password: 'blnk'
            },

            development: {
                selenium_host: 'qawinxp_global',
                selenium_port: 4445,
                blnk_url: 'http://blnk.com.es',
                blnk_user: 'weather@blnk.com.es',
                blnk_password: 'blnk'
            }
        }
    },
    ngtemplates:  {
        skywarp: {
            cwd: 'app',
            src: ['partials/*.html', 'partials/**/**/*.html'],
            dest: 'app/js/templates.js',
            options:    {
                htmlmin:  { collapseWhitespace: true, collapseBooleanAttributes: true },
                bootstrap:  function(module, script) {
                    return "/* NOTE: This file is autogenerated using grunt-angular-template */ \n\n define(['app'], function(app) { app.run(['$templateCache', function($templateCache) { "+script+" }])});";
                }
            }
        }
    }
});

grunt.loadNpmTasks('grunt-contrib-watch');
grunt.loadNpmTasks('grunt-contrib-less');
grunt.loadNpmTasks('grunt-contrib-clean');
grunt.loadNpmTasks('grunt-contrib-copy');
grunt.loadNpmTasks('grunt-contrib-uglify');
grunt.loadNpmTasks('grunt-contrib-cssmin');
grunt.loadNpmTasks('grunt-nightwatch');
grunt.loadNpmTasks('grunt-angular-templates');

grunt.registerTask('test', ['nightwatch']);
grunt.registerTask('build', ['less']);
grunt.registerTask('deploy-dev', ['clean:dist', 'less', 'ngtemplates', 'copy:main']);
grunt.registerTask('deploy', ['deploy-dev', 'uglify', 'cssmin']);

};
